In [1]:
!pip install transformers torch

In [2]:
import torch
from torch.optim import AdamW
from transformers import GPT2Config, GPT2Tokenizer, GPT2LMHeadModel, get_linear_schedule_with_warmup


c:\Users\KTS-WS-2501\Documents\composer-py\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
torch.cuda.is_available()

True

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [11]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

In [6]:
model = GPT2LMHeadModel.from_pretrained("gpt2")

c:\Users\KTS-WS-2501\Documents\composer-py\.venv\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\KTS-WS-2501\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 148/148 [00:00<00:00, 7926.82it/s]


In [30]:
text = "Who are you?."

In [31]:
ids = torch.tensor(tokenizer.encode([text]))
ids

tensor([[8241,  389,  345,   30,   13]])

In [32]:
output_ids = model.generate(ids)
output_ids

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
c:\Users\KTS-WS-2501\Documents\composer-py\.venv\Lib\site-packages\transformers\generation\utils.py:1616: UserWarning: Using the model-agnostic default `max_length` (=25) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


tensor([[ 8241,   389,   345,    30,    13,   198,   198,    40,  1101,   257,
          1310,  1643,   286,   257, 34712,    13,   314,  1101,   257,  1310,
          1643,   286,   257, 34712,    13]])

In [35]:
tokenizer.decode(output_ids)

["Who are you?.\n\nI'm a little bit of a nerd. I'm a little bit of a nerd."]

In [36]:
from transformers import GPT2Model

model = GPT2Model.from_pretrained("gpt2")
model

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 11828.00it/s]


GPT2Model(
  (wte): Embedding(50257, 768)
  (wpe): Embedding(1024, 768)
  (drop): Dropout(p=0.1, inplace=False)
  (h): ModuleList(
    (0-11): 12 x GPT2Block(
      (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (attn): GPT2Attention(
        (c_attn): Conv1D(nf=2304, nx=768)
        (c_proj): Conv1D(nf=768, nx=768)
        (attn_dropout): Dropout(p=0.1, inplace=False)
        (resid_dropout): Dropout(p=0.1, inplace=False)
      )
      (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
      (mlp): GPT2MLP(
        (c_fc): Conv1D(nf=3072, nx=768)
        (c_proj): Conv1D(nf=768, nx=3072)
        (act): NewGELUActivation()
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
)

In [42]:
model(ids).last_hidden_state.shape

torch.Size([1, 5, 768])

In [43]:
from transformers import AutoModelForCausalLM

In [44]:
model = AutoModelForCausalLM.from_pretrained("gpt2")

Loading weights: 100%|██████████| 148/148 [00:00<00:00, 10271.31it/s]


In [49]:
ids

tensor([[8241,  389,  345,   30,   13]])

In [45]:
model.generate(ids)

[transformers] The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
c:\Users\KTS-WS-2501\Documents\composer-py\.venv\Lib\site-packages\transformers\generation\utils.py:1616: UserWarning: Using the model-agnostic default `max_length` (=25) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


tensor([[ 8241,   389,   345,    30,    13,   198,   198,    40,  1101,   257,
          1310,  1643,   286,   257, 34712,    13,   314,  1101,   257,  1310,
          1643,   286,   257, 34712,    13]])

In [84]:
ids

tensor([[8241,  389,  345,   30,   13]])

In [85]:
out_ids = model.forward(ids).logits
out_ids.shape

torch.Size([1, 5, 50257])

In [74]:
last_out_id = out_ids[0,-1,:]
last_out_id.shape

torch.Size([50257])

In [78]:
out_prob = torch.softmax(last_out_id,dim=-1)
out_prob

tensor([5.1160e-05, 2.5179e-04, 1.0784e-04,  ..., 8.8873e-09, 9.1522e-09,
        6.6539e-03], grad_fn=<SoftmaxBackward0>)

In [82]:
out_id = torch.argmax(out_prob)
out_id

tensor(198)

In [83]:
tokenizer.decode(out_id)

'\n'